config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get :retired
    end
  end

  # Setting home page to users index page
  root to: 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def retired
    @users = User.where(status: 'Retired')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :gender, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kanri</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= email_field_tag 'user[email]', 'email@example.com', class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :gender %>
    <%= select_tag "user[gender]", options_for_select([ "Male", "Female" ], "Male"), class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :status %>
    <%= select_tag "user[status]", options_for_select([ "Member", "Retired" ], "Member"), class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary float-right' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="card mt-5">
  <div class="card-header">
    <h3>Editing User</h3>
  </div>

  <div class="card-body">

    <%= render 'form', user: @user %>

    <%= link_to 'Show', @user, class: 'btn btn-primary text-white' %> |
    <%= link_to 'Back', users_path, class: 'btn btn-danger text-white' %>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="card mt-5">
  <div class="card-header">
    <h3>
      Users
      <%= link_to 'Show Retired Users', retired_users_path, class: 'btn btn-primary text-white float-right' %>
    </h3>
  </div>
  <div class="card-body">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Gender</th>
          <th>Status</th>
          <th colspan="3" class="text-center">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.gender %></td>
            <td><%= user.status %></td>
            <td class="text-center">
              <%= link_to '<i class="fas fa-eye"></i>'.html_safe, user, class: 'btn btn-sm btn-primary text-white', title: 'Show' %>
              <%= link_to '<i class="fas fa-pencil-alt"></i>'.html_safe, edit_user_path(user), class: 'btn btn-sm btn-warning text-white', title: 'Edit' %>
              <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger text-white', title: 'Delete' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New User', new_user_path, class: "btn btn-primary text-white" %>
  </div>
</div>

app/views/users/new.html.erb
<div class="card mt-5">
  <div class="card-header">
    <h3>Create User</h3>
  </div>
  <div class="card-body">
    <%= render 'form', user: @user %>

    <%= link_to 'Back', users_path, class: 'btn btn-danger text-white' %>
  </div>
</div>

app/views/users/retired.html.erb
<p id="notice"><%= notice %></p>
<div class="card mt-5">
  <div class="card-header">
    <h3>
      Retired Users
      <%= link_to 'Show All Users', users_path, class: 'btn btn-danger text-white float-right' %>
    </h3>
  </div>
  <div class="card-body">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Gender</th>
          <th>Status</th>
          <th colspan="3" class="text-center">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.gender %></td>
            <td><%= user.status %></td>
            <td class="text-center">
              <%= link_to '<i class="fas fa-eye"></i>'.html_safe, user, class: 'btn btn-sm btn-primary text-white', title: 'Show' %>
              <%= link_to '<i class="fas fa-pencil-alt"></i>'.html_safe, edit_user_path(user), class: 'btn btn-sm btn-warning text-white', title: 'Edit' %>
              <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger text-white', title: 'Delete' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="card mt-5">
  <div class="card-header">
    <h3>Show User</h3>
  </div>
  <div class="card-body">
    <p id="notice"><%= notice %></p>
    <p>
      <strong>Name:</strong>
      <%= @user.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Gender:</strong>
      <%= @user.gender %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= @user.status %>
    </p>
    <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary text-white' %> |
    <%= link_to 'Back', users_path, class: 'btn btn-danger text-white' %>
  </div>
</div>